on: [push, pull_request]

name: Check and build schemas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build schemas
      uses: ArtifactDB/build-schemas-action@v0.2.0
      with:
        docs: public
        title: 'Bioconductor object schemas'

    - name: Publish to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.3
      if: github.ref == 'refs/heads/master'
      with:
        branch: gh-pages 
        folder: public
        target-folder: docs
        clean: true 

    - name: Bundle the release
      if: startsWith(github.ref, 'refs/tags/')
      run: tar -czvf bundle.tar.gz resolved

    - name: Publish release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bundle.tar.gz
